" syntax highlighting
syntax on

" lines numbers
set number
set relativenumber
"set numberwidth=5

"
" Plugins
" ===
"

" vim-code-dark
colorscheme codedark

"
" Statusline
"

set noshowmode " disable showing mode since we use lightline plugin